#!/usr/bin/env zsh

# Set default values for STOW_FOLDERS and DOTFILES if they are not already set
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,zsh,config,xsession,local,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Push into the DOTFILES directory
pushd $DOTFILES

# Iterate over each folder specified in STOW_FOLDERS
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    echo "NOTE:: stow $folder"
    stow -D $folder   # Unstow the folder
    stow $folder   # Stow the folder, adopting any existing files
done

# setup wallpaper feh
if command -v feh &> /dev/null; then
    feh --bg-fill $HOME/.dotfiles/assets/wallpaper/wallpaper.png
    echo "NOTE:: Default wallpaper set."
else
    echo "WARNING:: feh is not installed. Cannot set wallpaper."
fi


# Pop back to the original directory
popd
