#!/usr/bin/env zsh

# Set default values for STOW_FOLDERS and DOTFILES if they are not already set
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="tmux,zsh,config,xsession,local,git"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

# Define the source and destination directories
SOURCE_DIR="$HOME/.dotfiles/config/.config"
DEST_DIR="$HOME/.config"

# Get the current date in YYYYMMDD format
CURRENT_DATE=$(date +"%Y%m%d")

# Loop through each file/folder in the source directory
for item in "$SOURCE_DIR"/*; do
  # Get the base name of the item
  base_item=$(basename "$item")
  
  # Check if the item exists in the destination directory
  if [ -e "$DEST_DIR/$base_item" ]; then
    # If it exists, back it up by renaming
    mv "$DEST_DIR/$base_item" "$DEST_DIR/${base_item}_backup_$CURRENT_DATE"
  fi
 done

echo "Backuped completed of existing files." 
# Push into the DOTFILES directory
pushd $DOTFILES

# Iterate over each folder specified in STOW_FOLDERS
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g"); do
    echo "NOTE:: stow $folder"
    stow -D $folder   # Unstow the folder
    stow $folder   # Stow the folder, adopting any existing files
done

# setup wallpaper feh
if command -v feh &> /dev/null; then
    feh --bg-fill $HOME/.dotfiles/assets/wallpaper/wallpaper.png
    echo "NOTE:: Default wallpaper set."
else
    echo "WARNING:: feh is not installed. Cannot set wallpaper."
fi


# Pop back to the original directory
popd
