add_newline = false
# A minimal left prompt
format = """$directory$character"""
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = """$all"""
command_timeout = 1000

[directory]
home_symbol	= ' '
truncation_length = 8
truncation_symbol = '  '
format = '[$path ]($style)[$read_only]($read_only_style)'

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format =  '[$symbol$branch(:$remote_branch)]($style)'

[aws]
style = 'bold blue'
symbol = ""
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'

[kubernetes]
disabled = true
symbol = '󱃾'
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style)'
region = ""  # example "us-west-2"
account_id = "" # example "123456789012"
cluster_name = "" # example "ab-cde-fghe"
arn = "arn:aws:eks:$region:$account_id:cluster/$cluster_name"
contexts = [
  { context_pattern = "$arn", style = "green", context_alias = "Kubr", symbol = " " },
]

[golang]
symbol = ''
format = '[[ $symbol( $version) ](fg:teal bg:base)]($style)'

[nodejs]
symbol = ""
format = '[[ $symbol( $version) ](fg:green bg:base)]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ](fg:sapphire bg:base)]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ](fg:peach bg:base)]($style)'

[php]
symbol = ""
format = '[[ $symbol( $version) ](fg:lavender bg:base)]($style)'

[java]
symbol = ""
format = '[[ $symbol( $version) ](fg:yellow bg:base)]($style)'

[kotlin]
symbol = ""
format = '[[ $symbol( $version) ](fg:mauve bg:base)]($style)'

[haskell]
symbol = ""
format = '[[ $symbol( $version) ](fg:mauve bg:base)]($style)'

[python]
symbol = ""
format = '[[ $symbol( $version) (\($virtualenv\))](fg:blue bg:base)]($style)'

[docker_context]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $context) ](fg:blue bg:base)]($style)'

[conda]
symbol = ""
style = "bg:base"
format = '[[ $symbol( $environment) ](fg:green bg:base)]($style)'

[time]
disabled = false
time_format = "%r"
style = "bg:base"
format = '[[  $time ](fg:rosewater bg:base)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:blue)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:mauve)'
vimcmd_replace_symbol = '[](bold fg:mauve)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#00000000"
# base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

