hl.define_submap("global", function() end)

-- 1. Applications
hl.bind("SUPER + F1", hl.dsp.exec_cmd("noctalia msg panel-toggle blackbartblues/keymap:panel"), { description = "Keybind cheatsheet" })
hl.bind("SUPER + Return", hl.dsp.exec_cmd("command -v ghostty && exec ghostty || command -v kitty && exec kitty || command -v alacritty && exec alacritty || command -v konsole && exec konsole || command -v foot && exec foot || command -v wezterm && exec wezterm || command -v gnome-terminal && exec gnome-terminal || xterm"), { description = "Terminal" })
hl.bind("SUPER + D", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher"), { description = "App launcher" })
hl.bind("SUPER + S", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center"), { description = "Control center" })
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("noctalia msg screenshot-region"), { description = "Region screenshot" })
hl.bind("ALT + Tab", hl.dsp.exec_cmd("noctalia msg window-switcher"), { description = "Window switcher" })
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("noctalia msg session lock"), { locked = true, description = "Lock screen" })
-- 2. Noctalia Panels
hl.bind("SUPER + W", hl.dsp.exec_cmd("noctalia msg panel-toggle wallpaper"), { description = "Wallpaper panel" })
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("noctalia msg panel-toggle noctalia/wallhaven:browser"), { description = "Wallhaven browser" })
hl.bind("SUPER + SHIFT + period", hl.dsp.exec_cmd("noctalia msg settings-toggle"), { description = "Settings toggle" })
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("noctalia msg notification-dnd-toggle"), { description = "Do not disturb" })
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("noctalia msg nightlight-toggle"), { description = "Night light" })
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("noctalia msg bluetooth-toggle"), { description = "Bluetooth toggle" })
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("noctalia msg theme-mode-toggle"), { description = "Theme mode" })
hl.bind("SUPER + SHIFT + X", hl.dsp.exec_cmd("noctalia msg caffeine-toggle"), { description = "Caffeine mode" })
hl.bind("SUPER + N", hl.dsp.exec_cmd("noctalia msg panel-toggle control-center notifications"), { description = "Notifications panel" })
hl.bind("SUPER + semicolon", hl.dsp.exec_cmd("noctalia msg panel-toggle launcher /emo"), { description = "Emoji picker" })
hl.bind("SUPER + SHIFT + Y", hl.dsp.exec_cmd("noctalia msg dock-toggle"), { description = "Dock toggle" })
hl.bind("SUPER + B", hl.dsp.exec_cmd("noctalia msg panel-toggle noctalia/notes:panel"), { description = "Notes panel" })
hl.bind("SUPER + G", hl.dsp.exec_cmd("noctalia msg plugin noctalia/screen_recorder:service all toggle"), { description = "Screen recorder" })
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd("noctalia msg power-cycle"), { description = "Power menu" })
hl.bind("SUPER + SHIFT + V", hl.dsp.exec_cmd("noctalia msg panel-toggle clipboard"), { description = "Clipboard history" })
-- 3. Media Keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("noctalia msg volume-up"), { repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("noctalia msg volume-down"), { repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("noctalia msg volume-mute"), { locked = true, description = "Mute volume" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("noctalia msg mic-mute"), { locked = true, description = "Mute microphone" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("noctalia msg media toggle"), { locked = true, description = "Play/Pause" })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("noctalia msg media stop"), { locked = true, description = "Stop media" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("noctalia msg media previous"), { locked = true, description = "Previous track" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("noctalia msg media next"), { locked = true, description = "Next track" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("noctalia msg brightness-up"), { repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("noctalia msg brightness-down"), { repeating = true, description = "Brightness down" })
-- 4. App Shortcuts
hl.bind("SUPER + ALT + Q", hl.dsp.exec_cmd("app2unit -- zen-browser"), { description = "Firefox browser" })
hl.bind("SUPER + ALT + W", hl.dsp.exec_cmd("app2unit -- code"), { description = "Code editor" })
hl.bind("SUPER + ALT + E", hl.dsp.exec_cmd("app2unit -- dolphin"), { description = "File manager" })
hl.bind("SUPER + ALT + R", hl.dsp.exec_cmd("app2unit -- opencode"), { description = "AI assistant" })
hl.bind("SUPER + ALT + T", hl.dsp.exec_cmd("app2unit -- ghostty --command tmux"), { description = "Terminal + tmux" })
-- 5. Window Focus
hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }), { description = "Focus left" })
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }), { description = "Focus right" })
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }), { description = "Focus up" })
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }), { description = "Focus down" })
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }), { description = "Focus left (vim)" })
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }), { description = "Focus down (vim)" })
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }), { description = "Focus up (vim)" })
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }), { description = "Focus right (vim)" })
-- 6. Move Window
hl.bind("SUPER + CTRL + left", hl.dsp.window.move({ direction = "l" }), { repeating = true, description = "Move left" })
hl.bind("SUPER + CTRL + right", hl.dsp.window.move({ direction = "r" }), { repeating = true, description = "Move right" })
hl.bind("SUPER + CTRL + up", hl.dsp.window.move({ direction = "u" }), { repeating = true, description = "Move up" })
hl.bind("SUPER + CTRL + down", hl.dsp.window.move({ direction = "d" }), { repeating = true, description = "Move down" })
hl.bind("SUPER + CTRL + H", hl.dsp.window.move({ direction = "l" }), { repeating = true, description = "Move left (vim)" })
hl.bind("SUPER + CTRL + J", hl.dsp.window.move({ direction = "d" }), { repeating = true, description = "Move down (vim)" })
hl.bind("SUPER + CTRL + K", hl.dsp.window.move({ direction = "u" }), { repeating = true, description = "Move up (vim)" })
hl.bind("SUPER + CTRL + L", hl.dsp.window.move({ direction = "r" }), { repeating = true, description = "Move right (vim)" })
-- 7. Monitor Focus
hl.bind("SUPER + SHIFT + left", hl.dsp.focus({ direction = "left" }), { description = "Focus monitor left" })
hl.bind("SUPER + SHIFT + right", hl.dsp.focus({ direction = "right" }), { description = "Focus monitor right" })
hl.bind("SUPER + SHIFT + up", hl.dsp.focus({ direction = "up" }), { description = "Focus monitor up" })
hl.bind("SUPER + SHIFT + down", hl.dsp.focus({ direction = "down" }), { description = "Focus monitor down" })
hl.bind("SUPER + SHIFT + H", hl.dsp.focus({ direction = "left" }), { description = "Focus monitor left (vim)" })
hl.bind("SUPER + SHIFT + J", hl.dsp.focus({ direction = "down" }), { description = "Focus monitor down (vim)" })
hl.bind("SUPER + SHIFT + K", hl.dsp.focus({ direction = "up" }), { description = "Focus monitor up (vim)" })
hl.bind("SUPER + SHIFT + L", hl.dsp.focus({ direction = "right" }), { description = "Focus monitor right (vim)" })
-- 8. Move Window to Monitor
hl.bind("SUPER + SHIFT + CTRL + left", hl.dsp.window.move({ monitor = "l" }), { repeating = true, description = "Move to monitor left" })
hl.bind("SUPER + SHIFT + CTRL + right", hl.dsp.window.move({ monitor = "r" }), { repeating = true, description = "Move to monitor right" })
hl.bind("SUPER + SHIFT + CTRL + up", hl.dsp.window.move({ monitor = "u" }), { repeating = true, description = "Move to monitor up" })
hl.bind("SUPER + SHIFT + CTRL + down", hl.dsp.window.move({ monitor = "d" }), { repeating = true, description = "Move to monitor down" })
hl.bind("SUPER + SHIFT + CTRL + H", hl.dsp.window.move({ monitor = "l" }), { repeating = true, description = "Move to monitor left (vim)" })
hl.bind("SUPER + SHIFT + CTRL + J", hl.dsp.window.move({ monitor = "d" }), { repeating = true, description = "Move to monitor down (vim)" })
hl.bind("SUPER + SHIFT + CTRL + K", hl.dsp.window.move({ monitor = "u" }), { repeating = true, description = "Move to monitor up (vim)" })
hl.bind("SUPER + SHIFT + CTRL + L", hl.dsp.window.move({ monitor = "r" }), { repeating = true, description = "Move to monitor right (vim)" })
-- 9. Workspace Navigation
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "e+1" }), { repeating = true, description = "Next workspace" })
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = "e-1" }), { repeating = true, description = "Previous workspace" })
hl.bind("SUPER + U", hl.dsp.focus({ workspace = "e+1" }), { repeating = true, description = "Next workspace (vim)" })
hl.bind("SUPER + I", hl.dsp.focus({ workspace = "e-1" }), { repeating = true, description = "Previous workspace (vim)" })
hl.bind("SUPER + CTRL + Page_Down", hl.dsp.window.move({ workspace = "e+1" }), { repeating = true, description = "Move to next workspace" })
hl.bind("SUPER + CTRL + Page_Up", hl.dsp.window.move({ workspace = "e-1" }), { repeating = true, description = "Move to previous workspace" })
hl.bind("SUPER + CTRL + U", hl.dsp.window.move({ workspace = "e+1" }), { repeating = true, description = "Move to next workspace (vim)" })
hl.bind("SUPER + CTRL + I", hl.dsp.window.move({ workspace = "e-1" }), { repeating = true, description = "Move to previous workspace (vim)" })
hl.bind("SUPER + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "Next workspace (scroll)" })
hl.bind("SUPER + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "Previous workspace (scroll)" })
hl.bind("SUPER + CTRL + mouse_down", hl.dsp.window.move({ workspace = "e+1" }), { description = "Move to next workspace (scroll)" })
hl.bind("SUPER + CTRL + mouse_up", hl.dsp.window.move({ workspace = "e-1" }), { description = "Move to previous workspace (scroll)" })
-- 10. Workspace Switch
hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }), { description = "Workspace 1" })
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }), { description = "Workspace 2" })
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }), { description = "Workspace 3" })
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }), { description = "Workspace 4" })
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }), { description = "Workspace 5" })
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }), { description = "Workspace 6" })
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }), { description = "Workspace 7" })
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }), { description = "Workspace 8" })
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }), { description = "Workspace 9" })
hl.bind("SUPER + CTRL + 1", hl.dsp.window.move({ workspace = 1 }), { description = "Move to workspace 1" })
hl.bind("SUPER + CTRL + 2", hl.dsp.window.move({ workspace = 2 }), { description = "Move to workspace 2" })
hl.bind("SUPER + CTRL + 3", hl.dsp.window.move({ workspace = 3 }), { description = "Move to workspace 3" })
hl.bind("SUPER + CTRL + 4", hl.dsp.window.move({ workspace = 4 }), { description = "Move to workspace 4" })
hl.bind("SUPER + CTRL + 5", hl.dsp.window.move({ workspace = 5 }), { description = "Move to workspace 5" })
hl.bind("SUPER + CTRL + 6", hl.dsp.window.move({ workspace = 6 }), { description = "Move to workspace 6" })
hl.bind("SUPER + CTRL + 7", hl.dsp.window.move({ workspace = 7 }), { description = "Move to workspace 7" })
hl.bind("SUPER + CTRL + 8", hl.dsp.window.move({ workspace = 8 }), { description = "Move to workspace 8" })
hl.bind("SUPER + CTRL + 9", hl.dsp.window.move({ workspace = 9 }), { description = "Move to workspace 9" })
-- 11. Window Sizing
hl.bind("SUPER + minus", hl.dsp.exec_cmd("hyprctl dispatch resizeactive -10% 0"), { repeating = true, description = "Shrink width" })
hl.bind("SUPER + equal", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 10% 0"), { repeating = true, description = "Grow width" })
hl.bind("SUPER + SHIFT + minus", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 -10%"), { repeating = true, description = "Shrink height" })
hl.bind("SUPER + SHIFT + equal", hl.dsp.exec_cmd("hyprctl dispatch resizeactive 0 10%"), { repeating = true, description = "Grow height" })
-- 12. Window Management
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "maximized" }), { description = "Maximize" })
hl.bind("SUPER + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen" }), { description = "Fullscreen" })
hl.bind("SUPER + C", hl.dsp.window.center(), { description = "Center window" })
hl.bind("SUPER + T", hl.dsp.group.toggle(), { description = "Toggle tabbed group" })
hl.bind("SUPER + V", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.close(), { description = "Close window" })
-- 13. Screenshots
hl.bind("Print", hl.dsp.exec_cmd("noctalia msg screenshot-region"), { locked = true, description = "Region screenshot" })
hl.bind("CTRL + Print", hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen"), { locked = true, description = "Full screen screenshot" })
hl.bind("ALT + Print", hl.dsp.exec_cmd("noctalia msg screenshot-fullscreen all"), { locked = true, description = "All monitors screenshot" })
-- 15. Session
hl.bind("SUPER + SHIFT + E", hl.dsp.exit(), { description = "Exit Hyprland" })
hl.bind("CTRL + ALT + Delete", hl.dsp.exec_cmd("noctalia msg panel-toggle session"), { description = "Session menu" })
-- 16. Mouse
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Drag to move" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Drag to resize" })
