import = [ "~/.config/alacritty/schemes/everforest_dark.toml" ]

[window]
opacity = 1
blur = true
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

[env]
TERM = "xterm-256color"

[font]
size = 16

  [font.normal]
  family = "CaskaydiaCove Nerd Font"
  style = "Regular"
  [font.bold]
  family = "CaskaydiaCove Nerd Font"
  style = "Bold"
  [font.italic]
  family = "CaskaydiaCove Nerd Font"
  style = "Italic"


[shell]
program = "/usr/bin/zsh"


