import = [ "~/.config/alacritty/themes/themes/rose-pine.toml" ]

[window]
opacity = 1
blur = true
padding.x = 10
padding.y = 10

# decorations = "Buttonless"

[env]
TERM = "xterm-256color"

[font]
size = 12

  [font.offset]
  # x = 0 # for letter spacing
  # y = 8 # for line spacing 
  
  [font.normal]
  family = "Liga SFMono Nerd Font"
  style = "Regular"

[shell]
program = "/usr/bin/zsh"


