window:
  opacity: 1
import:
  - ~/.config/alacritty/themes/gruvbox_material.yml
env:
  TERM: xterm-256color
font:
  normal:
        family: FiraCode Nerd Font
        style: Regular
  # Point size
  size: 14.0
