import = [ "~/.config/alacritty/themes/rose-pine.toml" ]

[window]
opacity = 1

[env]
TERM = "xterm-256color"

[font]
size = 12

  [font.offset]
  x = 0 # for letter spacing
  y = 8 # for line spacing 
  
  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

[shell]
program = "/usr/bin/zsh"


