window:
  opacity: 0.9
import:
  - ~/.config/alacritty/catppuccin-mocha.yml
env:
  TERM: xterm-256color
font:
  normal:
        family: JetBrainsMono Nerd Font Mono
        style: Regular
  # Point size
  size: 14.0
